spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/spring_boot_jpa
    username:  springValidatorUser
    password:  spr1ngV4l1d4t0r.DB
    driverClassName: com.mysql.jdbc.Driver
    maxActive:  50
    maxIdle: 5
    minIdle: 25
    initialSize: 10
    validationQuery: SELECT 1
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    maxWait: 10000
    template:
    cache: false
  jpa:
    generateDdl: true
    hibernate:
      DdlAuto: update
  messages:
    basename: i18n/messages